export const AUTH = {
  LOGIN_WITH_EMAIL: {
    REQUEST: "LOGIN_WITH_EMAIL.REQUEST",
    SUCCESS: "LOGIN_WITH_EMAIL.SUCCESS",
    FAILURE: "LOGIN_WITH_EMAIL.FAILURE",
  },
  LOGOUT: {
    REQUEST: "LOGOUT.REQUEST",
    SUCCESS: "LOGOUT.SUCCESS",
    FAILURE: "LOGOUT.FAILURE",
  },
  REGISTER_WITH_EMAIL: {
    REQUEST: "REGISTER_WITH_EMAIL.REQUEST",
    SUCCESS: "REGISTER_WITH_EMAIL.SUCCESS",
    FAILURE: "REGISTER_WITH_EMAIL.FAILURE",
  },
  UPDATE_USER_NAME: {
    SUCCESS: "CREATE_USER.SUCCESS",
    FAILURE: "CREATE_USER.FAILURE",
  },
  SYNC_USER: "SYNC_USER",
};
